/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__ohos_media_audio_AudioRendererInfo__H
#define J4A__ohos_media_audio_AudioRendererInfo__H

#include "j4a/j4a_base.h"

jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__Builder(JNIEnv *env);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__Builder__catchAll(JNIEnv *env);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__Builder__asGlobalRef__catchAll(JNIEnv *env);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__audioStreamInfo(JNIEnv *env, jobject thiz, jobject audioStreamInfo);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__audioStreamInfo__catchAll(JNIEnv *env, jobject thiz, jobject audioStreamInfo);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__audioStreamInfo__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jobject audioStreamInfo);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__bufferSizeInBytes(JNIEnv *env, jobject thiz, jlong bufferSizeInBytes);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__bufferSizeInBytes__catchAll(JNIEnv *env, jobject thiz, jlong bufferSizeInBytes);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__bufferSizeInBytes__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jlong bufferSizeInBytes);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__isOffload(JNIEnv *env, jobject thiz, jboolean isOffload);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__isOffload__catchAll(JNIEnv *env, jobject thiz, jboolean isOffload);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__isOffload__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jboolean isOffload);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__audioStreamOutputFlag(JNIEnv *env, jobject thiz, jobject outputFlag);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__audioStreamOutputFlag__catchAll(JNIEnv *env, jobject thiz, jobject outputFlag);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__audioStreamOutputFlag__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jobject outputFlag);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__distributedDeviceId(JNIEnv *env, jobject thiz, jstring distributedDeviceId);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__distributedDeviceId__catchAll(JNIEnv *env, jobject thiz, jstring distributedDeviceId);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__distributedDeviceId__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jstring distributedDeviceId);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__distributedDeviceId__withCString(JNIEnv *env, jobject thiz, const char *distributedDeviceId_cstr__);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__distributedDeviceId__withCString__catchAll(JNIEnv *env, jobject thiz, const char *distributedDeviceId_cstr__);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__distributedDeviceId__withCString__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, const char *distributedDeviceId_cstr__);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__build(JNIEnv *env, jobject thiz);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__build__catchAll(JNIEnv *env, jobject thiz);
jobject J4AC_ohos_media_audio_AudioRendererInfo__Builder__build__asGlobalRef__catchAll(JNIEnv *env, jobject thiz);
int J4A_loadClass__J4AC_ohos_media_audio_AudioRendererInfo(JNIEnv *env);

#endif//J4A__ohos_media_audio_AudioRendererInfo__H
