/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "PacMap.h"

typedef struct J4AC_ohos_utils_PacMap {
    jclass id;

    jmethodID constructor_PacMap;
    jmethodID method_getIntValue;
    jmethodID method_putIntValue;
    jmethodID method_getString;
    jmethodID method_putString;
    jmethodID method_putSequenceableObjectList;
    jmethodID method_getLongValue;
    jmethodID method_putLongValue;
} J4AC_ohos_utils_PacMap;
static J4AC_ohos_utils_PacMap class_J4AC_ohos_utils_PacMap;

jobject J4AC_ohos_utils_PacMap__PacMap(JNIEnv *env)
{
    return (*env)->NewObject(env, class_J4AC_ohos_utils_PacMap.id, class_J4AC_ohos_utils_PacMap.constructor_PacMap);
}

jobject J4AC_ohos_utils_PacMap__PacMap__catchAll(JNIEnv *env)
{
    jobject ret_object = J4AC_ohos_utils_PacMap__PacMap(env);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_ohos_utils_PacMap__PacMap__asGlobalRef__catchAll(JNIEnv *env)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_ohos_utils_PacMap__PacMap__catchAll(env);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

jint J4AC_ohos_utils_PacMap__getIntValue(JNIEnv *env, jobject thiz, jstring key, jint defaultValue)
{
    return (*env)->CallIntMethod(env, thiz, class_J4AC_ohos_utils_PacMap.method_getIntValue, key, defaultValue);
}

jint J4AC_ohos_utils_PacMap__getIntValue__catchAll(JNIEnv *env, jobject thiz, jstring key, jint defaultValue)
{
    jint ret_value = J4AC_ohos_utils_PacMap__getIntValue(env, thiz, key, defaultValue);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jint J4AC_ohos_utils_PacMap__getIntValue__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__, jint defaultValue)
{
    jint ret_value = 0;
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__throwAny(env) || !key)
        goto fail;

    ret_value = J4AC_ohos_utils_PacMap__getIntValue(env, thiz, key, defaultValue);
    if (J4A_ExceptionCheck__throwAny(env)) {
        ret_value = 0;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &key);
    return ret_value;
}

jint J4AC_ohos_utils_PacMap__getIntValue__withCString__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__, jint defaultValue)
{
    jint ret_value = 0;
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !key)
        goto fail;

    ret_value = J4AC_ohos_utils_PacMap__getIntValue__catchAll(env, thiz, key, defaultValue);
    if (J4A_ExceptionCheck__catchAll(env)) {
        ret_value = 0;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &key);
    return ret_value;
}

void J4AC_ohos_utils_PacMap__putIntValue(JNIEnv *env, jobject thiz, jstring key, jint value)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_ohos_utils_PacMap.method_putIntValue, key, value);
}

void J4AC_ohos_utils_PacMap__putIntValue__catchAll(JNIEnv *env, jobject thiz, jstring key, jint value)
{
    J4AC_ohos_utils_PacMap__putIntValue(env, thiz, key, value);
    J4A_ExceptionCheck__catchAll(env);
}

void J4AC_ohos_utils_PacMap__putIntValue__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__, jint value)
{
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__throwAny(env) || !key)
        goto fail;

    J4AC_ohos_utils_PacMap__putIntValue(env, thiz, key, value);

fail:
    J4A_DeleteLocalRef__p(env, &key);
}

void J4AC_ohos_utils_PacMap__putIntValue__withCString__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__, jint value)
{
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !key)
        goto fail;

    J4AC_ohos_utils_PacMap__putIntValue__catchAll(env, thiz, key, value);

fail:
    J4A_DeleteLocalRef__p(env, &key);
}

jstring J4AC_ohos_utils_PacMap__getString(JNIEnv *env, jobject thiz, jstring key)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_ohos_utils_PacMap.method_getString, key);
}

jstring J4AC_ohos_utils_PacMap__getString__catchAll(JNIEnv *env, jobject thiz, jstring key)
{
    jstring ret_object = J4AC_ohos_utils_PacMap__getString(env, thiz, key);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jstring J4AC_ohos_utils_PacMap__getString__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jstring key)
{
    jstring ret_object   = NULL;
    jstring local_object = J4AC_ohos_utils_PacMap__getString__catchAll(env, thiz, key);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

const char *J4AC_ohos_utils_PacMap__getString__asCBuffer(JNIEnv *env, jobject thiz, jstring key, char *out_buf, int out_len)
{
    const char *ret_value = NULL;
    const char *c_str     = NULL;
    jstring local_string = J4AC_ohos_utils_PacMap__getString(env, thiz, key);
    if (J4A_ExceptionCheck__throwAny(env) || !local_string) {
        goto fail;
    }

    c_str = (*env)->GetStringUTFChars(env, local_string, NULL );
    if (J4A_ExceptionCheck__throwAny(env) || !c_str) {
        goto fail;
    }

    strlcpy(out_buf, c_str, out_len);
    ret_value = out_buf;

fail:
    J4A_ReleaseStringUTFChars__p(env, local_string, &c_str);
    J4A_DeleteLocalRef__p(env, &local_string);
    return ret_value;
}

const char *J4AC_ohos_utils_PacMap__getString__asCBuffer__catchAll(JNIEnv *env, jobject thiz, jstring key, char *out_buf, int out_len)
{
    const char *ret_value = NULL;
    const char *c_str     = NULL;
    jstring local_string = J4AC_ohos_utils_PacMap__getString__catchAll(env, thiz, key);
    if (J4A_ExceptionCheck__catchAll(env) || !local_string) {
        goto fail;
    }

    c_str = (*env)->GetStringUTFChars(env, local_string, NULL );
    if (J4A_ExceptionCheck__catchAll(env) || !c_str) {
        goto fail;
    }

    strlcpy(out_buf, c_str, out_len);
    ret_value = out_buf;

fail:
    J4A_ReleaseStringUTFChars__p(env, local_string, &c_str);
    J4A_DeleteLocalRef__p(env, &local_string);
    return ret_value;
}

jstring J4AC_ohos_utils_PacMap__getString__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__)
{
    jstring ret_object = NULL;
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__throwAny(env) || !key)
        goto fail;

    ret_object = J4AC_ohos_utils_PacMap__getString(env, thiz, key);
    if (J4A_ExceptionCheck__throwAny(env) || !ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &key);
    return ret_object;
}

jstring J4AC_ohos_utils_PacMap__getString__withCString__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__)
{
    jstring ret_object = NULL;
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !key)
        goto fail;

    ret_object = J4AC_ohos_utils_PacMap__getString__catchAll(env, thiz, key);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &key);
    return ret_object;
}

jstring J4AC_ohos_utils_PacMap__getString__withCString__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__)
{
    jstring ret_object   = NULL;
    jstring local_object = J4AC_ohos_utils_PacMap__getString__withCString__catchAll(env, thiz, key_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

const char *J4AC_ohos_utils_PacMap__getString__withCString__asCBuffer(JNIEnv *env, jobject thiz, const char *key_cstr__, char *out_buf, int out_len)
{
    const char *ret_value = NULL;
    const char *c_str     = NULL;
    jstring local_string = J4AC_ohos_utils_PacMap__getString__withCString(env, thiz, key_cstr__);
    if (J4A_ExceptionCheck__throwAny(env) || !local_string) {
        goto fail;
    }

    c_str = (*env)->GetStringUTFChars(env, local_string, NULL );
    if (J4A_ExceptionCheck__throwAny(env) || !c_str) {
        goto fail;
    }

    strlcpy(out_buf, c_str, out_len);
    ret_value = out_buf;

fail:
    J4A_ReleaseStringUTFChars__p(env, local_string, &c_str);
    J4A_DeleteLocalRef__p(env, &local_string);
    return ret_value;
}

const char *J4AC_ohos_utils_PacMap__getString__withCString__asCBuffer__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__, char *out_buf, int out_len)
{
    const char *ret_value = NULL;
    const char *c_str     = NULL;
    jstring local_string = J4AC_ohos_utils_PacMap__getString__withCString__catchAll(env, thiz, key_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !local_string) {
        goto fail;
    }

    c_str = (*env)->GetStringUTFChars(env, local_string, NULL );
    if (J4A_ExceptionCheck__catchAll(env) || !c_str) {
        goto fail;
    }

    strlcpy(out_buf, c_str, out_len);
    ret_value = out_buf;

fail:
    J4A_ReleaseStringUTFChars__p(env, local_string, &c_str);
    J4A_DeleteLocalRef__p(env, &local_string);
    return ret_value;
}

void J4AC_ohos_utils_PacMap__putString(JNIEnv *env, jobject thiz, jstring key, jstring value)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_ohos_utils_PacMap.method_putString, key, value);
}

void J4AC_ohos_utils_PacMap__putString__catchAll(JNIEnv *env, jobject thiz, jstring key, jstring value)
{
    J4AC_ohos_utils_PacMap__putString(env, thiz, key, value);
    J4A_ExceptionCheck__catchAll(env);
}

void J4AC_ohos_utils_PacMap__putString__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__, const char *value_cstr__)
{
    jstring key = NULL;
    jstring value = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__throwAny(env) || !key)
        goto fail;
    value = (*env)->NewStringUTF(env, value_cstr__);
    if (J4A_ExceptionCheck__throwAny(env) || !value)
        goto fail;

    J4AC_ohos_utils_PacMap__putString(env, thiz, key, value);

fail:
    J4A_DeleteLocalRef__p(env, &key);
    J4A_DeleteLocalRef__p(env, &value);
}

void J4AC_ohos_utils_PacMap__putString__withCString__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__, const char *value_cstr__)
{
    jstring key = NULL;
    jstring value = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !key)
        goto fail;
    value = (*env)->NewStringUTF(env, value_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !value)
        goto fail;

    J4AC_ohos_utils_PacMap__putString__catchAll(env, thiz, key, value);

fail:
    J4A_DeleteLocalRef__p(env, &key);
    J4A_DeleteLocalRef__p(env, &value);
}

void J4AC_ohos_utils_PacMap__putSequenceableObjectList(JNIEnv *env, jobject thiz, jstring key, jobject sequenceables)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_ohos_utils_PacMap.method_putSequenceableObjectList, key, sequenceables);
}

void J4AC_ohos_utils_PacMap__putSequenceableObjectList__catchAll(JNIEnv *env, jobject thiz, jstring key, jobject sequenceables)
{
    J4AC_ohos_utils_PacMap__putSequenceableObjectList(env, thiz, key, sequenceables);
    J4A_ExceptionCheck__catchAll(env);
}

void J4AC_ohos_utils_PacMap__putSequenceableObjectList__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__, jobject sequenceables)
{
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__throwAny(env) || !key)
        goto fail;

    J4AC_ohos_utils_PacMap__putSequenceableObjectList(env, thiz, key, sequenceables);

fail:
    J4A_DeleteLocalRef__p(env, &key);
}

void J4AC_ohos_utils_PacMap__putSequenceableObjectList__withCString__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__, jobject sequenceables)
{
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !key)
        goto fail;

    J4AC_ohos_utils_PacMap__putSequenceableObjectList__catchAll(env, thiz, key, sequenceables);

fail:
    J4A_DeleteLocalRef__p(env, &key);
}

jlong J4AC_ohos_utils_PacMap__getLongValue(JNIEnv *env, jobject thiz, jstring key)
{
    return (*env)->CallLongMethod(env, thiz, class_J4AC_ohos_utils_PacMap.method_getLongValue, key);
}

jlong J4AC_ohos_utils_PacMap__getLongValue__catchAll(JNIEnv *env, jobject thiz, jstring key)
{
    jlong ret_value = J4AC_ohos_utils_PacMap__getLongValue(env, thiz, key);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

jlong J4AC_ohos_utils_PacMap__getLongValue__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__)
{
    jlong ret_value = 0;
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__throwAny(env) || !key)
        goto fail;

    ret_value = J4AC_ohos_utils_PacMap__getLongValue(env, thiz, key);
    if (J4A_ExceptionCheck__throwAny(env)) {
        ret_value = 0;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &key);
    return ret_value;
}

jlong J4AC_ohos_utils_PacMap__getLongValue__withCString__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__)
{
    jlong ret_value = 0;
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !key)
        goto fail;

    ret_value = J4AC_ohos_utils_PacMap__getLongValue__catchAll(env, thiz, key);
    if (J4A_ExceptionCheck__catchAll(env)) {
        ret_value = 0;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &key);
    return ret_value;
}

void J4AC_ohos_utils_PacMap__putLongValue(JNIEnv *env, jobject thiz, jstring key, jlong value)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_ohos_utils_PacMap.method_putLongValue, key, value);
}

void J4AC_ohos_utils_PacMap__putLongValue__catchAll(JNIEnv *env, jobject thiz, jstring key, jlong value)
{
    J4AC_ohos_utils_PacMap__putLongValue(env, thiz, key, value);
    J4A_ExceptionCheck__catchAll(env);
}

void J4AC_ohos_utils_PacMap__putLongValue__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__, jlong value)
{
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__throwAny(env) || !key)
        goto fail;

    J4AC_ohos_utils_PacMap__putLongValue(env, thiz, key, value);

fail:
    J4A_DeleteLocalRef__p(env, &key);
}

void J4AC_ohos_utils_PacMap__putLongValue__withCString__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__, jlong value)
{
    jstring key = NULL;

    key = (*env)->NewStringUTF(env, key_cstr__);
    if (J4A_ExceptionCheck__catchAll(env) || !key)
        goto fail;

    J4AC_ohos_utils_PacMap__putLongValue__catchAll(env, thiz, key, value);

fail:
    J4A_DeleteLocalRef__p(env, &key);
}

int J4A_loadClass__J4AC_ohos_utils_PacMap(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_ohos_utils_PacMap.id != NULL)
        return 0;

    sign = "ohos/utils/PacMap";
    class_J4AC_ohos_utils_PacMap.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_ohos_utils_PacMap.id == NULL)
        goto fail;

    class_id = class_J4AC_ohos_utils_PacMap.id;
    name     = "<init>";
    sign     = "()V";
    class_J4AC_ohos_utils_PacMap.constructor_PacMap = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_ohos_utils_PacMap.constructor_PacMap == NULL)
        goto fail;

    class_id = class_J4AC_ohos_utils_PacMap.id;
    name     = "getIntValue";
    sign     = "(Ljava/lang/String;I)I";
    class_J4AC_ohos_utils_PacMap.method_getIntValue = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_ohos_utils_PacMap.method_getIntValue == NULL)
        goto fail;

    class_id = class_J4AC_ohos_utils_PacMap.id;
    name     = "putIntValue";
    sign     = "(Ljava/lang/String;I)V";
    class_J4AC_ohos_utils_PacMap.method_putIntValue = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_ohos_utils_PacMap.method_putIntValue == NULL)
        goto fail;

    class_id = class_J4AC_ohos_utils_PacMap.id;
    name     = "getString";
    sign     = "(Ljava/lang/String;)Ljava/lang/String;";
    class_J4AC_ohos_utils_PacMap.method_getString = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_ohos_utils_PacMap.method_getString == NULL)
        goto fail;

    class_id = class_J4AC_ohos_utils_PacMap.id;
    name     = "putString";
    sign     = "(Ljava/lang/String;Ljava/lang/String;)V";
    class_J4AC_ohos_utils_PacMap.method_putString = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_ohos_utils_PacMap.method_putString == NULL)
        goto fail;

    class_id = class_J4AC_ohos_utils_PacMap.id;
    name     = "putSequenceableObjectList";
    sign     = "(Ljava/lang/String;Ljava/util/ArrayList;)V";
    class_J4AC_ohos_utils_PacMap.method_putSequenceableObjectList = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_ohos_utils_PacMap.method_putSequenceableObjectList == NULL)
        goto fail;

    class_id = class_J4AC_ohos_utils_PacMap.id;
    name     = "getLongValue";
    sign     = "(Ljava/lang/String;)J";
    class_J4AC_ohos_utils_PacMap.method_getLongValue = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_ohos_utils_PacMap.method_getLongValue == NULL)
        goto fail;

    class_id = class_J4AC_ohos_utils_PacMap.id;
    name     = "putLongValue";
    sign     = "(Ljava/lang/String;J)V";
    class_J4AC_ohos_utils_PacMap.method_putLongValue = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_ohos_utils_PacMap.method_putLongValue == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "ohos.utils.PacMap");
    ret = 0;
fail:
    return ret;
}
