/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__ohos_media_common_Format__H
#define J4A__ohos_media_common_Format__H

#include "j4a/j4a_base.h"
#include <jni.h>

jobject J4AC_ohos_media_common_Format__Format(JNIEnv *env);
jobject J4AC_ohos_media_common_Format__Format__catchAll(JNIEnv *env);
jobject J4AC_ohos_media_common_Format__Format__asGlobalRef__catchAll(JNIEnv *env);


jint J4AC_ohos_media_common_Format__getIntValue(JNIEnv *env, jobject thiz, jstring key);
jint J4AC_ohos_media_common_Format__getIntValue__catchAll(JNIEnv *env, jobject thiz, jstring key);
jint J4AC_ohos_media_common_Format__getIntValue__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__);
jint J4AC_ohos_media_common_Format__getIntValue__withCString__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__);
void J4AC_ohos_media_common_Format__putIntValue(JNIEnv *env, jobject thiz, jstring key, jint value);
void J4AC_ohos_media_common_Format__putIntValue__catchAll(JNIEnv *env, jobject thiz, jstring key, jint value);

void J4AC_ohos_media_common_Format__putStringValue__withCString__catchAll(JNIEnv *env, jobject thiz,const char* key, const char* value);

void J4AC_ohos_media_common_Format__putIntValue__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__, jint value);
void J4AC_ohos_media_common_Format__putIntValue__withCString__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__, jint value);
void J4AC_ohos_media_common_Format__putObjectValue(JNIEnv *env, jobject thiz, jstring key, jobject value);

jobject J4AC_ohos_media_common_Format__getObjectValue__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__);


void J4AC_ohos_media_common_Format__putObjectValue__catchAll(JNIEnv *env, jobject thiz, jstring key, jobject value);
void J4AC_ohos_media_common_Format__putObjectValue__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__, jobject value);
void J4AC_ohos_media_common_Format__putObjectValue__withCString__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__, jobject value);
jstring J4AC_ohos_media_common_Format__getStringValue(JNIEnv *env, jobject thiz, jstring key);
jstring J4AC_ohos_media_common_Format__getStringValue__catchAll(JNIEnv *env, jobject thiz, jstring key);
jstring J4AC_ohos_media_common_Format__getStringValue__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jstring key);
const char *J4AC_ohos_media_common_Format__getStringValue__asCBuffer(JNIEnv *env, jobject thiz, jstring key, char *out_buf, int out_len);
const char *J4AC_ohos_media_common_Format__getStringValue__asCBuffer__catchAll(JNIEnv *env, jobject thiz, jstring key, char *out_buf, int out_len);
jstring J4AC_ohos_media_common_Format__getStringValue__withCString(JNIEnv *env, jobject thiz, const char *key_cstr__);
jstring J4AC_ohos_media_common_Format__getStringValue__withCString__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__);
jstring J4AC_ohos_media_common_Format__getStringValue__withCString__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__);
const char *J4AC_ohos_media_common_Format__getStringValue__withCString__asCBuffer(JNIEnv *env, jobject thiz, const char *key_cstr__, char *out_buf, int out_len);
const char *J4AC_ohos_media_common_Format__getStringValue__withCString__asCBuffer__catchAll(JNIEnv *env, jobject thiz, const char *key_cstr__, char *out_buf, int out_len);
int J4A_loadClass__J4AC_ohos_media_common_Format(JNIEnv *env);

#define J4A_HAVE_SIMPLE__J4AC_ohos_media_common_Format

#define J4AC_Format__Format J4AC_ohos_media_common_Format__Format
#define J4AC_Format__Format__asGlobalRef__catchAll J4AC_ohos_media_common_Format__Format__asGlobalRef__catchAll
#define J4AC_Format__Format__catchAll J4AC_ohos_media_common_Format__Format__catchAll
#define J4AC_Format__getIntValue J4AC_ohos_media_common_Format__getIntValue
#define J4AC_Format__getIntValue__catchAll J4AC_ohos_media_common_Format__getIntValue__catchAll
#define J4AC_Format__getIntValue__withCString J4AC_ohos_media_common_Format__getIntValue__withCString
#define J4AC_Format__getIntValue__withCString__catchAll J4AC_ohos_media_common_Format__getIntValue__withCString__catchAll
#define J4AC_Format__putIntValue J4AC_ohos_media_common_Format__putIntValue
#define J4AC_Format__putIntValue__catchAll J4AC_ohos_media_common_Format__putIntValue__catchAll
#define J4AC_Format__putIntValue__withCString J4AC_ohos_media_common_Format__putIntValue__withCString
#define J4AC_Format__putIntValue__withCString__catchAll J4AC_ohos_media_common_Format__putIntValue__withCString__catchAll
#define J4AC_Format__putObjectValue J4AC_ohos_media_common_Format__putObjectValue
#define J4AC_Format__putObjectValue__catchAll J4AC_ohos_media_common_Format__putObjectValue__catchAll
#define J4AC_Format__putObjectValue__withCString J4AC_ohos_media_common_Format__putObjectValue__withCString
#define J4AC_Format__putObjectValue__withCString__catchAll J4AC_ohos_media_common_Format__putObjectValue__withCString__catchAll
#define J4AC_Format__getStringValue J4AC_ohos_media_common_Format__getStringValue
#define J4AC_Format__getStringValue__asCBuffer J4AC_ohos_media_common_Format__getStringValue__asCBuffer
#define J4AC_Format__getStringValue__asCBuffer__catchAll J4AC_ohos_media_common_Format__getStringValue__asCBuffer__catchAll
#define J4AC_Format__getStringValue__asGlobalRef__catchAll J4AC_ohos_media_common_Format__getStringValue__asGlobalRef__catchAll
#define J4AC_Format__getStringValue__catchAll J4AC_ohos_media_common_Format__getStringValue__catchAll
#define J4AC_Format__getStringValue__withCString J4AC_ohos_media_common_Format__getStringValue__withCString
#define J4AC_Format__getStringValue__withCString__asCBuffer J4AC_ohos_media_common_Format__getStringValue__withCString__asCBuffer
#define J4AC_Format__getStringValue__withCString__asCBuffer__catchAll J4AC_ohos_media_common_Format__getStringValue__withCString__asCBuffer__catchAll
#define J4AC_Format__getStringValue__withCString__asGlobalRef__catchAll J4AC_ohos_media_common_Format__getStringValue__withCString__asGlobalRef__catchAll
#define J4AC_Format__getStringValue__withCString__catchAll J4AC_ohos_media_common_Format__getStringValue__withCString__catchAll
#define J4A_loadClass__J4AC_Format J4A_loadClass__J4AC_ohos_media_common_Format

#endif//J4A__ohos_media_common_Format__H
