/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__ohos_media_common_Source__H
#define J4A__ohos_media_common_Source__H

#include "j4a/j4a_base.h"

jobject J4AC_ohos_media_common_Source__Source(JNIEnv *env, jobject fd);
jobject J4AC_ohos_media_common_Source__Source__catchAll(JNIEnv *env, jobject fd);
jobject J4AC_ohos_media_common_Source__Source__asGlobalRef__catchAll(JNIEnv *env, jobject fd);
//jobject J4AC_ohos_media_common_Source__Source(JNIEnv *env, jobject fd, jlong offset, jlong len);
//jobject J4AC_ohos_media_common_Source__Source__catchAll(JNIEnv *env, jobject fd, jlong offset, jlong len);
//jobject J4AC_ohos_media_common_Source__Source__asGlobalRef__catchAll(JNIEnv *env, jobject fd, jlong offset, jlong len);
int J4A_loadClass__J4AC_ohos_media_common_Source(JNIEnv *env);

#endif//J4A__ohos_media_common_Source__H
